### PR TITLE
Add compress thread

### PR DESCRIPTION
**Pull request by xuan19970825**
Create new thread while latencyHistory.get(timeSlotBoundary) return null. This means the latencyHistory of earlier timeSlotBoundary was finish writing. So I can calculate the statistic data and over write the big dataset of that timeSlotBoundary to save the memory.

### CODE REVIEW

**Review by SLMT — CHANGES_REQUESTED** [review]
Thanks for your contribution. However, this implementation will not help reduce memory usage during benchmarking since `addTxnLatency` is only called when the benchmarker generates a report. I will tell you more details later.

**Comment by xuan19970825** [comment]
I have tried the new method and it ran well on my computer.

**Review by SLMT — CHANGES_REQUESTED** [review]
Great! Almost done. Please finish the following minor requests:

- Remove the commented code
- Ensure that `ZipThread` processes all the `TxnResultSet` in `resultSets` before it stops
- Merge your code with the latest master branch of our repository

**Comment by xuan19970825** [comment]
@SLMT 
Finish!!

**Review by SLMT — APPROVED** [review]
Great! Some parts require minor changes, but I can handle them. Thanks for your work.

**Pull request merged**
